import './Styles/globals.css';
import './Styles/todolist.css';
import { Inter } from 'next/font/google'
import AppContext from './Data Handler/Context';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App',
  description: 'Generated by Jesse 😉',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><AppContext>{children}</AppContext></body>  
    </html>
  )
}
