import './Styles/globals.css';
import { Inter } from 'next/font/google'
import AppContext from './Utils/context';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App',
  description: 'Generated by Jesse 😉',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AppContext>
      <body className={inter.className}>{children}</body>
    </AppContext>  
    </html>
  )
}
